[features]
seeds = false
[programs.localnet]
rental = "6R4xELxAKseqmCxS9Vf7VQya4FoEcY4roC7GRYyEf6Hx"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "localnet"
wallet = "/Users/bbev/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
